# Generated by Django 4.2.4 on 2023-08-09 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0005_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
